### ISSUE TITLE
An error occurred during the compilation of a resource required to process this request.

### ISSUE THREAD

**Issue by levkin77** [Platformus/Platformus-Sample#2]
VS2017
On navigate http://localhost:1234/backend/account/signin?returnurl=%2Fbackend%2F

An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.

Generated Code

The type 'Expression<TDelegate>' exists in both 'System.Linq.Expressions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Linq.Expressions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
+
        #pragma warning restore 1998
The type 'Expression<TDelegate>' exists in both 'System.Linq.Expressions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Linq.Expressions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
+
        #pragma warning restore 1998
The type 'Expression<TDelegate>' exists in both 'System.Linq.Expressions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Linq.Expressions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
+
        #pragma warning restore 1998

**Comment by DmitrySikorsky** [comment]
Hi! It is fixed in ExtCore 1.1.3. Platformus will be moved to VS2017 and ExtCore 1.1.3 in few days.
It was because of bug: https://github.com/ExtCore/ExtCore/issues/53

**Comment by DmitrySikorsky** [comment]
Fixed.
