### ISSUE TITLE
view error

### ISSUE THREAD

**Issue by mghalgar** [Platformus/Platformus-Sample#3]
hi , when i want to run , this error occurred:
InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Views/Installation/Index.en.cshtml
/Views/Installation/Index.cshtml
/Views/Shared/Index.en.cshtml
/Views/Shared/Index.cshtml

**Comment by mghalgar** [comment]
this error is solved by add config.json

**Comment by DmitrySikorsky** [comment]
Yes. The easiest way to run Platformus is downloading of the ready to use sample archive.
