### ISSUE TITLE
Great platform, I like GUI, workflow (approvals), Easier module extensions would be nice

### ISSUE THREAD

**Issue by mach37** [Platformus/Platformus-Sample#5]
Hi Dmitry 
Some links for you
I like your users/role management

 https://github.com/aspnetboilerplate/
 https://github.com/VelocityDB/VelocityDB
 https://github.com/dotnet-state-machine/stateless  (easy workflow)
 https://github.com/d-saravanan/multitenant.dev.template
 https://github.com/gabrielhws/DynamicMenu_ASPNET_MVC
 https://github.com/yohney/dto-generator
 https://github.com/DVILLAMIZARIT/Dashboard-16
 https://github.com/AvoBright/BootstrapLayouter
 https://github.com/kspearrin/Visual-Studio-jQuery-Code-Snippets
 https://github.com/OrchardCMS/Orchard
 http://haltu.github.io/muuri/
 https://github.com/Giannoudis/TimePeriodLibrary
 https://github.com/orosandrei/Rehosted-Workflow-Designer
 https://github.com/optimajet/WorkflowEngine.NET
 https://github.com/optimajet/DWKit

[Easy drag drop ](http://bit.ly/2qvaXvn)

just hoping to help provide input - I think this/hope will become better than orchard!

**Comment by DmitrySikorsky** [comment]
Thank you for you feedback, it is VERY important for me.
